- src/api/file-service.ts
- src/api/inventory-service.ts
- src/main/batch/Accept.ts
- src/main/component.ts
- src/main/db/scan_component_db.ts
- src/main/db/scan_files_db.ts
- src/main/db/scan_inventory_db.ts
- src/main/db/scan_results_db.ts
- src/main/inventory.ts
- src/main/results.ts
- src/main/services/LogicComponentService.ts
- src/main/services/LogicInventoryService.ts
- src/main/services/LogicResultService.ts
- src/renderer/features/workbench/pages/detected/pages/Editor/Editor.tsx
- src/renderer/hooks/useContextual.tsx
- Refactor on LogicComponentService and LogicInventoryService
- Pull apart logic from model
> Refactor component service inventory service

- src/renderer/context/DialogProvider.tsx
- src/renderer/features/workspace/pages/ProjectSettings/ProjectSettings.tsx
- src/renderer/ui/dialog/LicenseDialog.tsx
> License Button Finished

- src/main/db/querys_db.ts
- src/main/db/scan_component_db.ts
- src/main/db/scan_license_db.ts
- src/main/db/scan_results_db.ts
- src/main/helpers/LicenseHelper.ts
- src/main/services/LogicComponentService.ts
- src/main/services/LogicResultService.ts
- src/main/services/RescanLogicService.ts
- src/main/workspace/Metadata.ts
- src/main/workspace/Project.ts
- src/renderer/features/workbench/pages/detected/pages/ComponentDetail/ComponentDetail.tsx
- src/renderer/features/workbench/pages/detected/pages/ComponentList/components/IdentifiedList.tsx
- src/renderer/features/workbench/pages/detected/pages/Editor/Editor.tsx
- src/renderer/features/workspace/pages/ProjectSettings/ProjectSettings.tsx
- Adds list of license on result table
> DT-444 add list of licenses on results

- src/main/batch/Batch.ts
- src/main/batch/Identified.ts
- src/main/batch/Ignore.ts
- src/main/batch/Restore.ts
- src/main/db/querys_db.ts
- src/main/services/LogicInventoryService.ts
- Fixs minor bug on preload inventory dialog
- Fixs bug restore action. The restore action will restore all the files contained in a folder no matter the type of the file(filtered, match, no match)
> Fixs pre load inventory service

- src/main/db/ResultModel.ts
- src/main/inventory.ts
- src/main/services/LogicInventoryService.ts
-Improves perfomance on preload inventory service.
> DT-449 improve performance on preload inventory service

- src/main/db/querys_db.ts
- src/main/services/LogicComponentService.ts
- src/renderer/features/workbench/pages/detected/pages/ComponentDetail/ComponentDetail.tsx
-Fixs bug on component get files service
> Hot fix  component files

- src/main/export/format/SpdxLiteJson.ts
> Dt 459 update spdx output

- src/main/services/LogicInventoryService.ts
- src/renderer/ui/dialog/PreLoadInventoryDialog.tsx
- Avoids repeated components in the list
> Hotfix preload inventory dialog

- src/renderer/features/workbench/pages/report/Report.tsx
- src/renderer/features/workbench/store.tsx
- Shows the report identified screen when click  the report button and there is some identified or original file.
> DT-473 shows the report identified screen when identified files exists

- src/main/workspace/Project.ts
Fixed data being passed to scanner
> Fixed scanner input

- assets/exportTemplates/template.html
- src/renderer/features/workbench/pages/report/Report.scss
- src/renderer/features/workbench/pages/report/components/OssVsOriginalProgressBar.tsx
- Fixs bugs on oss vs original bar
- Adds percentage 
- Adds labels
> Hot fix oss vs original bar

- src/api/handlers/inventory.handler.ts
- src/main/batch/Ignore.ts
Fixes file tree status bug on ignore batch action
> Fixes update file tree status on ignore batch action

- src/renderer/features/workbench/components/AppBar/AppBar.tsx
Disables those export options that can't be exported without identification.
> DT-634 Fixes bug on export options without identification

- src/main/migration/scripts/110.ts
* Fixes SQLITE bug on result license insertion on migration 110
> DT-705 Fixes bug on result licenses insertion on migration 110

- package.json
- src/config/AppConfigDefault.ts
- src/main/task/componentCatalog/SearchComponentVersionTask.ts
- src/main/task/componentCatalog/gRPCConnection/GRPCConnection.ts
> Added api key to grpc services

- src/main/modules/export/format/HtmlSummary.ts
Fixes HTML report export when app is packaged
> DT-735 Fixes HTML report export when app is packaged

- src/main/migration/scripts/120.ts
- src/main/workspace/Project.ts
- src/main/workspace/ProjectZipper.ts
- Fixes bug when import project from zip file
> DT-758-Fixes bug on imported projects

- src/api/handlers/project.handler.ts
- src/main/task/scanner/BaseScannerTask.ts
- src/main/task/scanner/DependencyTask.ts
- src/main/task/scanner/ReScanTask.ts
- src/main/task/scanner/ResumeScanTask.ts
- src/main/task/scanner/ScanTask.ts
- src/main/task/scanner/ScannerPipelineTask.ts
-  Adds Scanner pipeline error 
-  Sends error via IPC to the front end
- Handles errors on scanner stages
> DT-888 handle errors on scanner pipeline

- src/api/services/project.service.ts
- src/main/task/IndexTreeTask/WFPIndexTreeTask.ts
- src/main/task/vulnerability/AddVulneravilityTask.ts
- Fixes bug when the user tries to create a new component and the API KEY has not been set.
> DT-908 Fixes bug on create component

- src/api/types.ts
- src/main/modules/projectKnowledge/projectKnowledgeAdapters/projectKnowledgeAdapter.ts
- src/renderer/ui/dialog/ProjectSelectorDialog.tsx
- Adds local files on the InventoryKnowledgeExtraction interface
- UI: Separates local files with commas
> DT-920 Adds local files on InventoryKnowledgeExtraction interface

- src/api/dto.ts
- src/api/types.ts
- src/main/model/queryBuilder/QueryBuilderCreator.ts
- src/main/model/queryBuilder/QueryBuilderMD5FileIn.ts
- src/main/model/querys_db.ts
- src/main/modules/projectKnowledge/ProjectKnowledgeExtractor.ts
- src/main/services/InventoryService.ts
- src/main/task/reuseIdentification/ReuseIdentificationTask.ts
- src/renderer/ui/dialog/ProjectSelectorDialog.tsx
- Adds reuse identification task
> DT-924 Adds reuse identification task

- src/main/main.ts
- src/main/services/UserSettingService.ts
- src/main/workspace/Workspace.ts
- Handle errors on corrupted workspace config
- Save invalid workspace config
- validate workspace configuration
> DT-474 Handle errors on corrupted workspace config

- .erb/override/override.example.config.json
- .erb/scripts/config-override.example.js
- .erb/scripts/override.js
- package.json
Co-Authored: Alejandro Perez <alejandro.perez@scanoss.com>
> DT-1187 Support rebrandring

- src/main/main.ts
- src/main/migration/AppMigration.ts
- src/main/migration/Migration.ts
- src/main/migration/scripts/0230.ts
- src/main/migration/scripts/1.12.0.ts
- src/main/services/UserSettingService.ts
Co-authored-by: Agustin Isasmendi <isasmendi.agus@gmail.com>
> DT-1221 Adds workspace migration

- src/api/handlers/project.handler.ts
- src/api/index.ts
- src/api/middlewares/lock.middleware.ts
- src/api/middlewares/project.open.permissions.middleware.ts
- src/api/middlewares/project.permissions.middleware.ts
- src/api/middlewares/ws.permissions.middleware.ts
- src/main/model/Connection.ts
- src/main/model/project/ProjectModel.ts
- src/main/model/project/models/FileModel.ts
- src/main/model/workspace/WorkspaceModel.ts
- src/main/services/ModelProvider.ts
- src/main/services/UserSettingService.ts
- src/main/workspace/Workspace.ts
Co-authored-by: Agustin Isasmendi <isasmendi.agus@gmail.com>
> DT-1229 Handle file system permissions

- README.md
- release/app/package.json
- src/main/migration/AppMigration.ts
- src/main/migration/scripts/1.12.0.ts
- src/main/migration/scripts/1.12.3.ts
- src/main/migration/scripts/183.ts
- src/main/services/UserSettingService.ts
Co-authored-by: Agustin Isasmendi <isasmendi.agus@gmail.com>
Co-authored-by: Franco Stramana <franco.stramana@gmail.com>
> DT-1265 Fixes bug on migration 1.12.0

- src/renderer/features/workbench/components/KeywordGroupMenu/KeywordGroupMenu.scss
- src/renderer/features/workbench/components/KeywordGroupMenu/KeywordGroupMenu.tsx
- src/renderer/features/workspace/pages/ProjectSettings/ProjectSettings.tsx
- src/renderer/store/workbench-store/workbenchSlice.ts
- src/renderer/store/workspace-store/workspaceSlice.ts
- src/renderer/ui/dialog/SettingsDialog.tsx
The PR includes:
- Fix: APIs are not refreshing on the project settings screen.
- Chore: The keyword group dialog now includes an accept button.
> SP-949 apis not refreshing on project setting screen

- package-lock.json
- package.json
- src/renderer/features/workbench/pages/report/components/MatchesForLicense.tsx
What:
- Show file count on each matched component
> feat: [SP-1137] Add number of files matched for each component

- src/main/task/cryptography/AddCryptographyTask.ts
- src/main/task/grpc/gRPCConnection/gRPCConnection.ts
- src/main/task/scanner/dependency/DependencyTask.ts
- src/main/task/scanner/vulnerability/VulnerabilitiesTask.ts
- src/main/task/vulnerability/AddVulnerabilityTask.ts
Fixes bug on gRPC proxy settings
> bug: SP-1217 Fixes bug on gRPC proxy settings

- .github/workflows/publish.yml
- Upgrades actions/download-artifact to v4
> bug: SP-1557 Fixes Sign with CodeSignTool job

- .github/workflows/publish.yml
> hotfix: SP-1557 Fixes create release job

- src/renderer/ui/dialog/SettingsDialog.tsx
- Hides API KEY on SettingsDialog.tsx
> chore:SP-1685 Hides API KEY on Settings Dialog

- src/main/task/scanner/adapter/CodeScannerInputAdapter.ts
- Improved error logging for context files
> chore:Improves error message for invalid context files

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- src/main/model/project/models/VulnerabilityModel.ts
- src/main/services/ProjectService.ts
- src/main/task/cryptography/AddCryptographyTask.ts
- src/main/task/scanner/ScannerFactory.ts
- src/main/task/scanner/dependency/DependencyTask.ts
- src/main/task/vulnerability/AddVulnerabilityTask.ts
- Integrated SCANOSS free decoration services using the scanoss.js SDK
- Implemented REST protocol for SCANOSS free decoration services
> Chore/integrate scanoss free decoration services via scanoss SDK
